import dotenv from 'dotenv';

dotenv.config();

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const RESEND_FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'RTooth Clinic <onboarding@resend.dev>';

/**
 * Base function to send an email using Resend API via native fetch
 */
export const sendEmail = async ({ to, subject, html }) => {
  if (!RESEND_API_KEY) {
    console.warn(`\n[EMAIL SERVICE WARNING] RESEND_API_KEY is not defined. Email mock-printed to console:`);
    console.warn(`--------------------------------------------------`);
    console.warn(`TO: ${to}`);
    console.warn(`FROM: ${RESEND_FROM_EMAIL}`);
    console.warn(`SUBJECT: ${subject}`);
    console.warn(`BODY SUMMARY:`);
    console.warn(html.replace(/<[^>]*>/g, ' ').slice(0, 500) + '...');
    console.warn(`--------------------------------------------------\n`);
    return { success: true, mock: true };
  }

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: RESEND_FROM_EMAIL,
        to: Array.isArray(to) ? to : [to],
        subject,
        html
      })
    });

    const data = await response.json();
    if (!response.ok) {
      throw new Error(data.message || `Resend API returned status ${response.status}`);
    }

    console.log(`[EMAIL SERVICE] Email successfully sent to ${to}. ID: ${data.id}`);
    return { success: true, id: data.id };
  } catch (error) {
    console.error(`[EMAIL SERVICE ERROR] Failed to send email to ${to}:`, error.message);
    throw error;
  }
};

/**
 * Helper to build standard clinical email container html
 */
const buildEmailTemplate = (title, contentHTML) => {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${title}</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f8fafc; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; color: #1e293b; line-height: 1.6;">
      <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #f8fafc; padding: 32px 16px;">
        <tr>
          <td align="center">
            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px; background-color: #ffffff; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
              
              <!-- Brand Header -->
              <tr>
                <td style="background-color: #0ea5e9; background: linear-gradient(135deg, #0284c7 0%, #0369a1 100%); padding: 32px 24px; text-align: center;">
                  <h1 style="color: #ffffff; margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.02em;">RTooth Clinical Portal</h1>
                  <p style="color: #e0f2fe; margin: 8px 0 0 0; font-size: 14px; font-weight: 500;">Clinical Intelligence & Patient Monitoring</p>
                </td>
              </tr>
              
              <!-- Email Body Content -->
              <tr>
                <td style="padding: 36px 24px;">
                  ${contentHTML}
                </td>
              </tr>

              <!-- Footer -->
              <tr>
                <td style="background-color: #f8fafc; border-top: 1px solid #e2e8f0; padding: 24px; text-align: center; font-size: 12px; color: #64748b;">
                  <p style="margin: 0;">This email is automatically generated by the RTooth Clinic Portal.</p>
                  <p style="margin: 4px 0 0 0;">&copy; 2026 RTooth Inc. | Confidential Health Information System</p>
                </td>
              </tr>

            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `;
};

/**
 * Triggered when a patient logs symptoms. Sent to the assigned doctor.
 */
export const sendSymptomNotificationEmail = async ({ doctorEmail, doctorName, patientName, patientCode, symptoms }) => {
  const painColor = symptoms.pain_scale >= 7 ? '#ef4444' : symptoms.pain_scale >= 4 ? '#f59e0b' : '#10b981';
  const bleedingText = symptoms.bleeding === true || symptoms.bleeding === 'true' ? 'Yes (Active Bleeding)' : 'No';
  const bleedingColor = symptoms.bleeding === true || symptoms.bleeding === 'true' ? '#ef4444' : '#1e293b';

  const bodyContent = `
    <h2 style="color: #0f172a; font-size: 18px; margin-top: 0; margin-bottom: 16px;">Symptom Log Logged</h2>
    <p style="margin-bottom: 24px; font-size: 15px; color: #334155;">
      Hello Dr. <strong>${doctorName}</strong>,
      <br><br>
      Your assigned patient, <strong>${patientName}</strong> (Code: <code>${patientCode}</code>), has submitted a new daily symptom report. Details are recorded below:
    </p>

    <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 24px;">
      <h3 style="margin-top: 0; margin-bottom: 12px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b;">Reported Parameters</h3>
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr style="border-bottom: 1px solid #f1f5f9;">
          <td style="padding: 8px 0; font-weight: 600; color: #475569; width: 50%;">Pain Scale Score:</td>
          <td style="padding: 8px 0; font-weight: 700; color: ${painColor};">${symptoms.pain_scale} / 10</td>
        </tr>
        <tr style="border-bottom: 1px solid #f1f5f9;">
          <td style="padding: 8px 0; font-weight: 600; color: #475569;">Burning Sensation:</td>
          <td style="padding: 8px 0; font-weight: 600;">${symptoms.burning_sensation}</td>
        </tr>
        <tr style="border-bottom: 1px solid #f1f5f9;">
          <td style="padding: 8px 0; font-weight: 600; color: #475569;">Mouth Opening Limit:</td>
          <td style="padding: 8px 0; font-weight: 600;">${symptoms.difficulty_opening_mouth}</td>
        </tr>
        <tr style="border-bottom: 1px solid #f1f5f9;">
          <td style="padding: 8px 0; font-weight: 600; color: #475569;">Ulcer Duration:</td>
          <td style="padding: 8px 0; font-weight: 600;">${symptoms.ulcer_duration} days</td>
        </tr>
        <tr>
          <td style="padding: 8px 0; font-weight: 600; color: #475569;">Bleeding Present:</td>
          <td style="padding: 8px 0; font-weight: 700; color: ${bleedingColor};">${bleedingText}</td>
        </tr>
      </table>
    </div>

    <p style="font-size: 14px; color: #64748b; margin-bottom: 24px;">
      If the symptoms are critical or show rapid regression, please schedule a clinical appointment.
    </p>

    <div style="text-align: center;">
      <a href="${process.env.APP_URL || 'http://localhost:5000'}/login" style="background-color: #0284c7; color: #ffffff; padding: 12px 24px; border-radius: 6px; font-weight: 600; text-decoration: none; display: inline-block;">View Patient Case Profile</a>
    </div>
  `;

  const html = buildEmailTemplate(`Symptom Log Update: ${patientName}`, bodyContent);
  return sendEmail({
    to: doctorEmail,
    subject: `[RTooth Alert] Symptom log submitted by ${patientName} (${patientCode})`,
    html
  });
};

/**
 * Sent to a patient when a doctor creates/logs a clinical visit checkup.
 */
export const sendVisitSummaryEmail = async ({ patientEmail, patientName, doctorName, checkup, prescriptions }) => {
  const followUpDateStr = checkup.next_checkup_date 
    ? new Date(checkup.next_checkup_date).toLocaleDateString(undefined, { dateStyle: 'long' }) 
    : 'No follow-up date scheduled';

  let medsHtml = '';
  if (prescriptions && prescriptions.length > 0) {
    medsHtml = `
      <h3 style="font-size: 15px; margin-top: 24px; margin-bottom: 12px; color: #334155;">Prescribed Medications</h3>
      <table border="0" cellpadding="8" cellspacing="0" width="100%" style="border-collapse: collapse; border: 1px solid #e2e8f0; border-radius: 6px; overflow: hidden; margin-bottom: 24px;">
        <thead>
          <tr style="background-color: #f1f5f9;">
            <th align="left" style="font-weight: 600; font-size: 13px; color: #475569; border-bottom: 1px solid #e2e8f0;">Medication</th>
            <th align="left" style="font-weight: 600; font-size: 13px; color: #475569; border-bottom: 1px solid #e2e8f0;">Dosage</th>
            <th align="left" style="font-weight: 600; font-size: 13px; color: #475569; border-bottom: 1px solid #e2e8f0;">Frequency</th>
          </tr>
        </thead>
        <tbody>
          ${prescriptions.map(med => `
            <tr>
              <td style="font-size: 13.5px; border-bottom: 1px solid #e2e8f0; color: #1e293b; font-weight: 600;">${med.medication_name}</td>
              <td style="font-size: 13.5px; border-bottom: 1px solid #e2e8f0; color: #475569;">${med.dosage}</td>
              <td style="font-size: 13.5px; border-bottom: 1px solid #e2e8f0; color: #475569;">${med.frequency}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;
  }

  const bodyContent = `
    <h2 style="color: #0f172a; font-size: 18px; margin-top: 0; margin-bottom: 16px;">Clinical Checkup Summary</h2>
    <p style="margin-bottom: 24px; font-size: 15px; color: #334155;">
      Dear <strong>${patientName}</strong>,
      <br><br>
      Thank you for visiting RTooth Clinic today. Below is a summary of your consultation session with Dr. <strong>${doctorName}</strong>:
    </p>

    <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 24px;">
      <h3 style="margin-top: 0; margin-bottom: 8px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b;">Visit Findings</h3>
      <p style="margin: 0; font-size: 14.5px; color: #1e293b; font-style: italic;">"${checkup.findings}"</p>
      
      ${checkup.recommendations ? `
        <h3 style="margin-top: 16px; margin-bottom: 8px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b;">Recommendations</h3>
        <p style="margin: 0; font-size: 14px; color: #1e293b;">${checkup.recommendations}</p>
      ` : ''}
    </div>

    ${medsHtml}

    <div style="background-color: #ecfdf5; border: 1px solid #a7f3d0; border-radius: 8px; padding: 20px; margin-bottom: 24px; text-align: center;">
      <h3 style="margin-top: 0; margin-bottom: 6px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; color: #065f46;">Scheduled Follow-Up</h3>
      <p style="margin: 0; font-size: 16px; font-weight: 700; color: #047857;">${followUpDateStr}</p>
      ${checkup.followup_notes ? `<p style="margin: 6px 0 0 0; font-size: 13.5px; color: #065f46;">${checkup.followup_notes}</p>` : ''}
    </div>

    <p style="font-size: 14px; color: #64748b; margin-bottom: 24px;">
      Please ensure you take all medications exactly as prescribed and continue logging your symptoms on the portal daily.
    </p>

    <div style="text-align: center;">
      <a href="${process.env.APP_URL || 'http://localhost:5000'}/login" style="background-color: #0284c7; color: #ffffff; padding: 12px 24px; border-radius: 6px; font-weight: 600; text-decoration: none; display: inline-block;">Log In to Patient Portal</a>
    </div>
  `;

  const html = buildEmailTemplate(`Clinical Checkup Summary`, bodyContent);
  return sendEmail({
    to: patientEmail,
    subject: `Your RTooth consultation summary with Dr. ${doctorName}`,
    html
  });
};

/**
 * Sent to a patient as a reminder for an upcoming appointment.
 */
export const sendUpcomingAppointmentReminderEmail = async ({ patientEmail, patientName, doctorName, nextCheckupDate, notes }) => {
  const dateStr = new Date(nextCheckupDate).toLocaleDateString(undefined, { dateStyle: 'full' });
  const timeStr = new Date(nextCheckupDate).toLocaleTimeString(undefined, { timeStyle: 'short' });

  const bodyContent = `
    <h2 style="color: #0f172a; font-size: 18px; margin-top: 0; margin-bottom: 16px;">Appointment Reminder</h2>
    <p style="margin-bottom: 24px; font-size: 15px; color: #334155;">
      Dear <strong>${patientName}</strong>,
      <br><br>
      This is a friendly reminder that you have an upcoming clinical checkup scheduled at RTooth Clinic:
    </p>

    <div style="background-color: #f0f9ff; border: 1px solid #bae6fd; border-radius: 8px; padding: 20px; margin-bottom: 24px; text-align: center;">
      <h3 style="margin-top: 0; margin-bottom: 6px; font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; color: #0369a1;">Appointment Time</h3>
      <p style="margin: 0; font-size: 18px; font-weight: 700; color: #0284c7;">${dateStr}</p>
      <p style="margin: 4px 0 0 0; font-size: 14px; font-weight: 600; color: #0369a1;">Time: ${timeStr}</p>
      <p style="margin: 12px 0 0 0; font-size: 14px; color: #0f172a;">Practitioner: <strong>Dr. ${doctorName}</strong></p>
    </div>

    ${notes ? `
      <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
        <strong style="font-size: 13px; color: #64748b; text-transform: uppercase; display: block; margin-bottom: 6px;">Follow-up Notes</strong>
        <span style="font-size: 14px; color: #1e293b;">${notes}</span>
      </div>
    ` : ''}

    <p style="font-size: 14px; color: #64748b; margin-bottom: 24px;">
      If you need to reschedule or cancel your appointment, please contact the clinic or sign in to the portal as soon as possible.
    </p>

    <div style="text-align: center;">
      <a href="${process.env.APP_URL || 'http://localhost:5000'}/login" style="background-color: #0284c7; color: #ffffff; padding: 12px 24px; border-radius: 6px; font-weight: 600; text-decoration: none; display: inline-block;">View Appointment in Portal</a>
    </div>
  `;

  const html = buildEmailTemplate(`Appointment Reminder`, bodyContent);
  return sendEmail({
    to: patientEmail,
    subject: `Reminder: Upcoming check-up tomorrow at RTooth Clinic`,
    html
  });
};

/**
 * Sent to a doctor containing a daily summary of patients with severe symptoms.
 */
export const sendSevereSymptomsDigestEmail = async ({ doctorEmail, doctorName, severeLogs }) => {
  const listHtml = severeLogs.map(log => {
    const bleedingText = log.bleeding ? 'Yes' : 'No';
    const timeStr = new Date(log.logged_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    
    return `
      <tr style="border-bottom: 1px solid #e2e8f0;">
        <td style="padding: 12px 8px; font-size: 13px; font-weight: 600; color: #1e293b;">
          ${log.patient_name}<br>
          <code style="font-size:11px;color:#64748b;">${log.patient_code}</code>
        </td>
        <td style="padding: 12px 8px; font-size: 13px; font-weight: 700; color: #ef4444; text-align: center;">
          ${log.pain_scale}
        </td>
        <td style="padding: 12px 8px; font-size: 13px; color: #334155;">
          Burning: ${log.burning_sensation}<br>
          Mouth: ${log.difficulty_opening_mouth}
        </td>
        <td style="padding: 12px 8px; font-size: 13px; color: #ef4444; font-weight: 600; text-align: center;">
          ${bleedingText}
        </td>
        <td style="padding: 12px 8px; font-size: 12px; color: #64748b; text-align: right;">
          ${timeStr}
        </td>
      </tr>
    `;
  }).join('');

  const bodyContent = `
    <h2 style="color: #0f172a; font-size: 18px; margin-top: 0; margin-bottom: 16px;">Daily Severe Symptoms Alert Digest</h2>
    <p style="margin-bottom: 24px; font-size: 15px; color: #334155;">
      Hello Dr. <strong>${doctorName}</strong>,
      <br><br>
      The system has identified <strong>${severeLogs.length}</strong> of your assigned patients who logged critical, high-risk, or severe symptoms in the last 24 hours:
    </p>

    <table border="0" cellpadding="8" cellspacing="0" width="100%" style="border-collapse: collapse; border: 1px solid #e2e8f0; border-radius: 6px; overflow: hidden; margin-bottom: 24px;">
      <thead>
        <tr style="background-color: #f8fafc; border-bottom: 2px solid #e2e8f0;">
          <th align="left" style="font-weight: 600; font-size: 12px; color: #475569; padding: 12px 8px;">Patient</th>
          <th align="center" style="font-weight: 600; font-size: 12px; color: #475569; padding: 12px 8px; width: 60px;">Pain</th>
          <th align="left" style="font-weight: 600; font-size: 12px; color: #475569; padding: 12px 8px;">Severe Symptoms</th>
          <th align="center" style="font-weight: 600; font-size: 12px; color: #475569; padding: 12px 8px; width: 70px;">Bleed</th>
          <th align="right" style="font-weight: 600; font-size: 12px; color: #475569; padding: 12px 8px;">Time</th>
        </tr>
      </thead>
      <tbody>
        ${listHtml}
      </tbody>
    </table>

    <p style="font-size: 14px; color: #64748b; margin-bottom: 24px;">
      Please review these cases on the clinical dashboard and reach out to patients requiring intervention.
    </p>

    <div style="text-align: center;">
      <a href="${process.env.APP_URL || 'http://localhost:5000'}/login" style="background-color: #0284c7; color: #ffffff; padding: 12px 24px; border-radius: 6px; font-weight: 600; text-decoration: none; display: inline-block;">Sign In to Clinical Dashboard</a>
    </div>
  `;

  const html = buildEmailTemplate(`Severe Symptoms Daily Digest`, bodyContent);
  return sendEmail({
    to: doctorEmail,
    subject: `[RTooth Summary] Daily Severe Symptom Digest: ${severeLogs.length} cases require attention`,
    html
  });
};
